---
title: "R_NDVI"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages used

```{r}
library(raster)
library(rgdal)
library(rgeos)
#library(reticulate)
#library(RColorBrewer)
library(tidyverse)
```

## Input Datasets

```{r}
folder <- "Inputs"
filez <- as.list(list.files(folder, full.names = TRUE))
trefry_study <- c(readOGR("Study_Areas/trefry_study.shp"))
```

## Scripts

```{r}
Calculate_NDVI <- function(NIR_band, Red_band){
  NDVI <- (NIR_band - Red_band) / (NIR_band + Red_band)
  return(NDVI)
}
NDVI_from_filename <- function(filename, study_area){
  sTime <-  Sys.time()
  #getting new filename using the date of the original image
  date <- gsub(".*/", "", filename)
  date <- gsub("_.*", "", date)
  new_filename <- paste(date, "NDVI_points", sep = "_")
  
  #convert from filename to a brick raster as these are apparently faster for calculation
  multi <- filename %>% stack() %>% brick()
  
  #clip the raster by the input study area
  multi <- crop(multi, study_area)
  
  #calculating NDVI
  #apparently using overlay with a premade function is faster, but this is the same as calling the function
  NDVI <- overlay(multi[[4]], multi[[3]], fun = Calculate_NDVI)
  
  #convert from raster to point, add date in the second column
  NDVI_points <- rasterToPoints(NDVI, spatial = TRUE)
  
  NDVI_points$Date <- date
  
  #save into outputs folder
  writeOGR(NDVI_points, dsn = "Outputs", layer = new_filename, driver = "ESRI Shapefile", overwrite_layer = TRUE)
  
  eTime <-  Sys.time()
  transpired <- eTime - sTime
  print(transpired)
  
  return(NDVI_points)
}
```

## Create Files
test is defined as a list first to hopefully make it go faster, i think i read it does that somewhere

```{r}
test <- vector(mode = "list", length = length(filez))
test <- map2(filez, trefry_study, NDVI_from_filename)
```

## Merge Shapefiles

```{r eval = FALSE}
sTime <- Sys.time()
NDVI_merged <- do.call(bind, test[1:3])
eTime <- Sys.time()
elapsed <- eTime - sTime
print(elapsed)
```

## Save Merged Shapefile

```{r eval = FALSE}
writeOGR(NDVI_merged, dsn = "Outputs", layer = "NDVI_merged", driver = "ESRI Shapefile", overwrite_layer = TRUE)
```