---
title: "R_NDVI_Raster_to_Raster"
author: "Evan Muise"
date: "06/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages used

```{r}
library(raster)
library(rgdal)
library(rgeos)
library(tidyverse)
#library(reticulate)
#library(RColorBrewer)
```

## Input Datasets

```{r}
folder <- "Inputs"
filez <- as.list(list.files(folder, full.names = TRUE))
study <- c(readOGR("Study_Areas/trefry_study.shp"))
```

## Scripts

```{r}
Calculate_NDVI <- function(NIR_band, Red_band){
  NDVI <- (NIR_band - Red_band) / (NIR_band + Red_band)
  return(NDVI)
}
NDVI_from_filename <- function(filename, study_area){
  sTime <-  Sys.time()
  #getting new filename using the date of the original image
  date <- gsub(".*/", "", filename)
  date <- gsub("_.*", "", date)
  new_filename <- paste("NDVI", date, sep = "_")
  new_filename <- paste(new_filename, ".tif", sep = "")
  
  #convert from filename to a brick raster as these are apparently faster for calculation
  multi <- filename %>% stack() %>% brick()
  
  #clip the raster by the input study area
  multi <- crop(multi, study_area)
  
  #calculating NDVI
  #apparently using overlay with a premade function is faster, but this is the same as calling the function
  NDVI <- overlay(multi[[4]], multi[[3]], fun = Calculate_NDVI)
  
  #save into outputs folder
  writeRaster(NDVI, filename = file.path("R_Outputs", new_filename), format = "GTiff", overwrite = TRUE)
  
  eTime <-  Sys.time()
  transpired <- eTime - sTime
  print(transpired)
  
  return(NDVI)
}
```

## Create Files
test is defined as a list first to hopefully make it go faster, i think i read it does that somewhere

```{r}
#test <- vector(mode = "list", length = length(filez))
eTime <- Sys.time()
test <- map2(filez, study, NDVI_from_filename)
sTime <- Sys.time()
print(sTime - eTime)
```


